//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_detalle_factura
    {
        public int pk_id_detallefactura { get; set; }
        public Nullable<int> fk_id_producto { get; set; }
        public Nullable<int> fk_id_factura { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual p_facturas p_facturas { get; set; }
        public virtual p_productos p_productos { get; set; }
    }
}
