//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_facturas()
        {
            this.p_detalle_factura = new HashSet<p_detalle_factura>();
        }
    
        public int pk_id_factura { get; set; }
        public Nullable<int> fk_id_cliente { get; set; }
        public string v_valor_total { get; set; }
        public Nullable<System.DateTime> d_fecha_compra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_detalle_factura> p_detalle_factura { get; set; }
        public virtual p_persona p_persona { get; set; }
    }
}
