//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_persona()
        {
            this.p_facturas = new HashSet<p_facturas>();
        }
    
        public int pk_id_persona { get; set; }
        public Nullable<int> fk_id_tipodoc { get; set; }
        public string v_numero_documento { get; set; }
        public string v_nombre { get; set; }
        public string v_razon_social { get; set; }
        public Nullable<System.DateTime> d_fecha_nacimiento { get; set; }
    
        public virtual c_tipo_documento c_tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_facturas> p_facturas { get; set; }
    }
}
